artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  csv_path: data/UrbanSound8K.csv
  preprocess_dir: artifacts/data_ingestion/preprocess
  preprocess_data_dir: artifacts/data_ingestion/preprocess/mfccs.csv
  audio_dataset_path: 'data\\raw'
  split_dir: artifacts/data_ingestion/splits
  train_data_dir: artifacts/data_ingestion/splits/train.csv
  test_data_dir: artifacts/data_ingestion/splits/test.csv



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/audio_classification.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/audio_classification_model.h5
  train_data_dir: artifacts/data_ingestion/splits/train.csv
  test_data_dir: artifacts/data_ingestion/splits/test.csv
  checkpoint_model_filepath: artifacts/training/checkpoint_dir/model.h5
  base_model_path: artifacts/prepare_base_model/audio_classification.h5